import paramiko, sys, time

TASKS = [

# ── TASK-6: Critical data fixes ────────────────────────────────────────────
"""[TASK-6: CRITICAL DATA FIXES] Working directory: /home/hibug/FORGE-Bench. Fix three high-impact data errors in dataset/annotations/samples.json. (1) micro_lat_001 Q2 answer key is INVERTED: find the sample with task_id="micro_lat_001", find the question containing "copper trace routes maintain their routing paths", change its "answer" field from "no" to "yes". Rationale: the question asks whether traces are preserved — on success they ARE preserved, so the correct answer is yes. (2) Fix domain field for sensitivity samples: find all samples whose task_id starts with "SA", "SB", or "SC" and currently have "domain": "unknown" or missing domain. Set their domain based on their task_id prefix: SA* -> "aerospace", SB* -> "energy" (if SB exists), SC* -> "manufacturing" (if SC exists). Specifically for SA01, SA02, SA03: set "domain": "aerospace". (3) Fix constraint_annotations inconsistency: scan ALL samples in samples.json and verify that each sample has the required fields: task_id, domain, topology_type, failure_target, text, image_path, vfa_target, questions (list with at least 1 item each having q and answer fields), constraint_annotations (dict with at least topology_type key). For any sample missing required fields, add sensible defaults or raise a clear error message to a log. (4) Run validation: python3 -c "import json; s=json.load(open('dataset/annotations/samples.json')); errors=[]; [errors.append(f'{x[\"task_id\"]}: missing domain') for x in s if x.get('domain','')=='unknown']; [errors.append(f'{x[\"task_id\"]}: Q answer empty') for x in s for q in x.get('questions',[]) if not q.get('answer')]; print('Errors:', errors or 'NONE')" and confirm zero errors. Commit: git -c http.proxy=http://127.0.0.1:7897 add dataset/annotations/samples.json && git -c http.proxy=http://127.0.0.1:7897 commit -m 'data: fix micro_lat_001 Q2 answer key, SA sensitivity domains, constraint_annotations validation'.""",

# ── TASK-7: GI surface + kinematic algorithm fixes ─────────────────────────
"""[TASK-7: GI SURFACE & KINEMATIC ALGORITHM FIXES] Working directory: /home/hibug/FORGE-Bench. Fix two critical algorithmic issues in geometric integrity evaluation. PART A - eval/geometric_integrity/surface.py: (1) Read the full file. Find where the GI score is computed from chamfer distance — locate the formula like `score = 1.0 - min(mean_cd / threshold, 1.0)` or similar. Add a perspective-conditioning mechanism: the function signature likely accepts frames or a vfa_score parameter — if vfa_score is passed and vfa_score > 0.30, add field 'gi_orbit_conditioning': True to the output dict and compute a CONDITIONED score using per-frame delta CD (difference between consecutive frames) rather than anchor-to-final CD. The conditioned score formula should be: conditioned_cd = mean of abs(cd[i] - cd[i-1]) for i in 1..N, score = 1.0 - min(conditioned_cd / (threshold * 0.3), 1.0). Also enforce floor: final_score = max(0.10, raw_score). (2) Add a `perspective_correction_applied` boolean field to all surface GI output dicts. PART B - eval/geometric_integrity/kinematic.py: (1) Read the full file. Find the adjacency matrix variance threshold (likely around 25.0). Replace the hardcoded threshold with a percentile-based approach: compute variance across all frames first, then use the 80th percentile of frame-wise variances as the reference scale. Score formula: score = max(0.10, 1.0 - min(mean_variance / (ref_scale * 5.0), 1.0)). This makes the threshold adaptive rather than a magic number. (2) For the dark background fix: add function `is_dark_background(frame)` that returns True if more than 40% of pixels (converted to grayscale) are below value 30. In the optical flow computation, if is_dark_background(first_frame): crop frames to center 60% ROI (h1=int(H*0.2), h2=int(H*0.8), w1=int(W*0.2), w2=int(W*0.8)) before computing flow; also lower static detection threshold from 0.8 to 0.5 px/frame. (3) Add field 'dark_background_detected': bool to kinematic GI output. After changes run python3 -m py_compile eval/geometric_integrity/surface.py eval/geometric_integrity/kinematic.py. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'eval/gi: perspective-conditioned surface CD, adaptive kinematic variance, dark-bg ROI'.""",

# ── TASK-8: GI sub-algorithm fixes ─────────────────────────────────────────
"""[TASK-8: GI SUB-ALGORITHM ROBUSTNESS FIXES] Working directory: /home/hibug/FORGE-Bench. Fix four GI sub-algorithm issues. (1) eval/geometric_integrity/rotary.py — Hough Circle confidence: read full file. After calling cv2.HoughCircles(), add validation: if circles is None or len(circles[0]) == 0: return {'score': None, 'error': 'hough_no_circles', 'method': 'rotational_symmetry'}. If len(circles[0]) > 3: return {'score': None, 'error': 'hough_ambiguous_circles', 'method': 'rotational_symmetry'}. Only proceed with single unambiguous circle detection. (2) eval/geometric_integrity/track_chain.py — Adaptive ROI: read full file. Find the hardcoded ROI fraction (likely 0.55, 0.88, 0.05, 0.95 or similar). Replace with adaptive detection: try current ROI first; if the periodicity score in that ROI is below 0.3, systematically try 4 alternative ROI bands (top 30%, bottom 30%, left 40%, right 40%) and use the band with the highest periodicity score. Add field 'roi_band_used': str describing which band was selected. (3) eval/geometric_integrity/symmetry_mech.py — Asymmetric guard: read full file. After computing the best axis symmetry score, add: if best_score < 0.25: return {'score': None, 'error': 'no_bilateral_symmetry_detected', 'method': 'bilateral_symmetry', 'note': 'mechanism may be intentionally asymmetric'}. Do not return 0.0 for structures with no bilateral symmetry — None is more honest. (4) eval/geometric_integrity/lattice.py — SIFT threshold: read full file. Find _MIN_MATCHES constant, change from 8 to 20. Additionally if fewer than 20 matches found but more than 5: return {'score': 0.25, 'insufficient_keypoints': True, 'n_matches': n, 'method': 'sift_homography', 'note': 'below recommended 20 matches, score unreliable'}. If fewer than 5: return None. Run py_compile on all 4 files. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'eval/gi: rotary circle confidence, adaptive track ROI, symmetry guard, SIFT min-match 20'.""",

# ── TASK-9: VFA algorithm fixes ─────────────────────────────────────────────
"""[TASK-9: VFA ALGORITHM FIXES] Working directory: /home/hibug/FORGE-Bench. Fix three VFA evaluation issues. Read eval/vfa/eval.py completely first. (1) Orbit angle accumulation error (line ~155): find where frame-to-frame rotation angles are accumulated. Replace the current `total += abs(r)` summation logic with anchor-to-final single estimation: compute RANSAC affine transform between FIRST frame and LAST frame only (not pairwise). If the first-to-last RANSAC fails (fewer than 4 inliers), try first-to-second-to-last, then return vfa=None with vfa_uncalculable=True if all fail. Do NOT accumulate pairwise angles — this amplifies errors. Update the orbit branch accordingly. (2) Dark background ROI optical flow (line ~380): find the global static detection using mean flow magnitude. Add: at the start of VFA evaluation, compute `dark_bg = np.mean(cv2.cvtColor(frames[0], cv2.COLOR_BGR2GRAY)) < 40`. If dark_bg: (a) lower static threshold from 0.8 to 0.5 px/frame, (b) compute flow only on center 60% ROI of each frame pair. Add 'dark_background': dark_bg to the vfa_detail output dict. (3) VLM fallback documentation and stub: find the comment referencing 'GPT fallback for crane samples'. Replace the misleading comment with a proper NotImplementedError stub: if motion_type == 'crane' and vfa_uncalculable: raise NotImplementedError('Crane VFA requires VLM fallback — see GitHub issue #TODO. For now, return None.') and return {'vfa': None, 'vfa_uncalculable': True, 'note': 'crane_vlm_fallback_not_implemented'}. This is honest about the limitation rather than silently failing. (4) Add field 'vfa_estimation_method' to all VFA output dicts: values should be 'anchor_to_final_ransac', 'center_roi_flow', 'pairwise_accumulated' (legacy, to be deprecated), or 'static_detected'. Run python3 -m py_compile eval/vfa/eval.py. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'eval/vfa: anchor-to-final orbit, dark-bg ROI, crane stub, estimation method tagging'.""",

# ── TASK-10: Scoring & pipeline robustness ──────────────────────────────────
"""[TASK-10: SCORING & PIPELINE ROBUSTNESS] Working directory: /home/hibug/FORGE-Bench. Fix six scoring and pipeline issues. (1) RIF gating by VFA: in scoring/aggregate.py or scoring/per_sample.py, find where RIF is included in the output. Add logic: if vfa_score is not None and vfa_score < 0.05 (essentially static video): set rif_gated=None in the output and add note 'rif_excluded_static_video'. Include rif_gated as a separate field alongside rif so consumers know it was excluded. (2) Pre-flight video path check: create a new function check_dataset_integrity(samples_json_path, video_root) in eval/run.py (or a new file eval/preflight.py): loads samples.json, for each sample with a non-null video_path, checks os.path.exists(video_path). Prints a summary: 'Found N/M videos. Missing: [list of task_ids]'. Call this function at the start of any eval run and log results to results/{model}/preflight.log. (3) Resolution normalization: in all GI evaluation modules, at the point where frames are read from video, add: TARGET_H, TARGET_W = 720, 1280. If frame.shape[:2] != (TARGET_H, TARGET_W): frame = cv2.resize(frame, (TARGET_W, TARGET_H), interpolation=cv2.INTER_AREA). Apply this consistently before any pixel-based metric computation. Add a config constant EVAL_RESOLUTION = (720, 1280) at the top of eval/geometric_integrity/__init__.py. (4) Lucas-Kanade window auto-scale: find all cv2.calcOpticalFlowPyrLK calls with hardcoded winSize=(21,21). Replace with: win = max(11, int(min(H, W) / 40)); winSize=(win, win). Apply to all optical flow calls in eval/vfa/eval.py and eval/geometric_integrity/kinematic.py. (5) Codec frame count validation: in any module that reads video frame count via cv2.CAP_PROP_FRAME_COUNT, after getting the count, validate by seeking to the last frame: cap.set(cv2.CAP_PROP_POS_FRAMES, reported_count - 1); ret, _ = cap.read(). If ret is False: binary search for actual last readable frame, use that as actual_count. Log warning if actual_count < reported_count * 0.9. (6) Run python3 -m py_compile on all modified files and python3 -c "import eval.geometric_integrity, eval.vfa.eval, scoring.aggregate, scoring.per_sample; print('OK')". Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'pipeline: RIF VFA-gating, preflight check, resolution normalization, LK auto-scale, codec validation'.""",

# ── TASK-11: Eval methodology improvements ───────────────────────────────────
"""[TASK-11: EVAL METHODOLOGY IMPROVEMENTS] Working directory: /home/hibug/FORGE-Bench. Improve four evaluation methodology weaknesses. (1) PP domain-specific failure checklists: read eval/physical_plausibility/eval.py completely. Find the domain_hints dict or equivalent prompt-building logic. Replace vague domain descriptions with per-sample failure mode checklists loaded from samples.json constraint_annotations. The new prompt format should include: 'For this specific sample, check these observable physical constraints: {list from constraint_annotations.hard_constraints}. Each constraint either holds or is violated — score accordingly.' If constraint_annotations.hard_constraints is empty for a sample, fall back to the current domain hint. Modify the PP evaluator to accept and inject the sample-specific constraints into the LLM prompt. (2) IKA superlative success handling: read eval/domain_alignment/ (find the IKA evaluation script). Find where question answers are compared against expected answers from samples.json. Add logic: if expected_answer == 'no' and model_answer == 'yes': check if the question phrasing contains failure-predictive language ('merging', 'disappearing', 'distortion', 'breaking', 'collapse', 'drift'). If yes AND the model answer includes reasoning that explicitly confirms structural correctness (not just 'yes'), flag as 'superlative_pass': True and score as CORRECT (not as wrong). Log these cases to results/{model}/superlative_passes.log. (3) Sweep motion decomposition: find VFA sweep computation in eval/vfa/eval.py. Find where orbit and crane components are blended (60/40). Add separate output fields: 'vfa_orbit_component': float and 'vfa_crane_component': float alongside the blended 'vfa'. Update scoring/per_sample.py to pass through these component fields into the per-sample result JSON. (4) Expose RIF and Fourier weights as config: in eval/geometric_integrity/lattice_fourier.py find the percentile threshold (97.0), move to top-of-file constant SPECTRAL_PEAK_PERCENTILE = 97.0 with comment explaining it. In scoring/aggregate.py or eval/reference_fidelity/eval.py find the RIF formula (0.5 * SSIM + 0.5 * hist_corr), extract weights to constants RIF_WEIGHT_SSIM = 0.5 and RIF_WEIGHT_HIST = 0.5 with comment noting these are unvalidated defaults. Run py_compile and import test. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'eval: PP sample-specific constraints, IKA superlative-pass, sweep decomposition, expose config constants'.""",

# ── TASK-12: JSON schema + samples.json validation ───────────────────────────
"""[TASK-12: JSON SCHEMA & DATASET VALIDATION] Working directory: /home/hibug/FORGE-Bench. Add formal validation to the dataset. (1) Create dataset/schema.json defining the required structure of each entry in samples.json using JSON Schema draft-07 format. Required fields and types: task_id (string, pattern ^[a-z]{2,6}_[a-z]{2,8}_[0-9]{3}$|^S[A-Z][0-9]{2}$), domain (string, enum: [aerospace, microelectronics, robotics, energy, vehicle, manufacturing]), topology_type (string, enum: [surface, lattice, kinematic]), failure_target (string, minLength: 10), text (string, minLength: 20), image_path (string, pattern: ^dataset/images/), vfa_target (string), questions (array, minItems: 2, each item must have q:string and answer:string with enum [yes, no]), constraint_annotations (object, required: [topology_type]), reverse (boolean), extra_frame (integer). (2) Create dataset/validate.py: loads samples.json and schema.json, uses jsonschema library (pip install jsonschema if needed), validates every entry, prints PASS or lists all violations with field paths. Run it: python3 dataset/validate.py. Fix any violations found in samples.json. (3) Add a GitHub Actions workflow file .github/workflows/validate.yml that runs python3 dataset/validate.py on every push to main. Content: name: Validate Dataset, on: push branches: [main], jobs: validate: runs-on: ubuntu-latest, steps: checkout, setup-python 3.11, pip install jsonschema, python dataset/validate.py. (4) Add dataset/annotations/README.md documenting the schema fields with one-line descriptions for each. (5) Run python3 dataset/validate.py and confirm zero errors. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'dataset: add JSON schema, validation script, GitHub Actions workflow, annotations README'.""",

# ── TASK-13: Dataset expansion ───────────────────────────────────────────────
"""[TASK-13: DATASET EXPANSION TO ~80 SAMPLES] Working directory: /home/hibug/FORGE-Bench. Expand samples.json from current ~30 to ~80 total samples. Goal: ~13 samples per domain, all topology types covered, all motion types represented. Read current samples.json first to understand existing coverage and avoid duplicates. ADD new samples across these specific gaps: AEROSPACE (need 8 more): 2 kinematic samples (landing gear retraction orbit, jet engine compressor pan), 2 tilt/rise samples (commercial airliner nose-up tilt, cargo plane vertical rise), 2 dolly samples (Boeing 747 engine nacelle dolly-in, cockpit windshield dolly-in), 1 lattice sample (jet engine turbine blade array orbit), 1 surface sample (Airbus A380 wing flex during orbit). VEHICLE (need 8 more): 2 kinematic (crane boom extension kinematic, excavator arm hydraulic kinematic), 2 lattice (container ship deck container grid orbit, suspension bridge cable array pan), 2 surface (cargo ship hull orbit, mining truck orbit), 1 dolly (truck engine bay dolly-in), 1 tilt (tower crane vertical rise). ENERGY (need 5 more): 2 kinematic (wind turbine blade rotation, pump jack oscillation), 1 tilt (offshore platform vertical rise), 1 dolly (solar panel cell grid dolly-in), 1 surface (wind farm turbine array orbit). MANUFACTURING (need 5 more): 2 kinematic (conveyor belt lateral pan, delta-arm robot pick-and-place), 1 surface (CNC machine bed orbit), 1 tilt (assembly line vertical rise), 1 dolly (3D printer nozzle dolly-in). ROBOTICS (need 5 more): 2 kinematic (quadruped robot walk gait, robotic arm welding), 1 surface (FANUC robot arm orbit), 1 dolly (end effector dolly-in), 1 cross-topology (humanoid robot landing gear analogy — arm-to-body kinematic + surface). MICROELECTRONICS (need 5 more): 2 lattice (BGA solder ball array, via hole grid), 1 kinematic (wire bond oscillation), 1 dolly (die surface dolly-in), 1 surface (wafer surface orbit). For EVERY new sample: task_id follows existing naming convention, failure_target is domain-specific and scientifically plausible, questions array has 3-4 IKA questions with yes/no answers targeting the failure mode, image_path=dataset/images/{domain}/{task_id}.jpg, create a _NEEDS_IMAGE.txt spec at that path. Validate with python3 dataset/validate.py after adding. Run: python3 -c "import json; s=json.load(open('dataset/annotations/samples.json')); d={}; [d.update({x['domain']:d.get(x['domain'],0)+1}) for x in s]; print(f'Total: {len(s)}'); print(d)" to show counts per domain. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'dataset: expand to ~80 samples across all 6 domains, all topology types and motion types covered'.""",

]

TODO_HEADER = """\
# FORGE-Bench 龙虾任务列表 (v3 — full 27-issue fix plan)
# ============================================================
# 当前队列：先完成现有 TASK-3/4/5，然后依次执行 TASK-6 到 TASK-13
# ============================================================

"""

def stream(client, cmd, timeout=30):
    chan = client.get_transport().open_session()
    chan.exec_command(cmd)
    chan.settimeout(timeout)
    while True:
        if chan.recv_ready():
            d = chan.recv(4096).decode("utf-8", errors="replace")
            sys.stdout.buffer.write(d.encode("gbk", errors="replace"))
            sys.stdout.flush()
        if chan.exit_status_ready():
            time.sleep(0.2)
            while chan.recv_ready():
                d = chan.recv(4096).decode("utf-8", errors="replace")
                sys.stdout.buffer.write(d.encode("gbk", errors="replace"))
                sys.stdout.flush()
            break
        time.sleep(0.05)

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('192.168.248.77', username='hibug', password='mug2025', timeout=10)

# Read current todo to preserve TASK-3/4/5
sftp = client.open_sftp()
with sftp.open('/home/hibug/lobster/todo.md', 'r') as f:
    current = f.read().decode('utf-8')

# Extract existing tasks (TASK-3/4/5) that are still pending
existing_tasks = [l for l in current.split('\n')
                  if l.startswith('[TASK-') and not l.startswith('[TASK-6')]

# Build new todo: header + existing pending + new tasks 6-13
new_todo = TODO_HEADER
for t in existing_tasks:
    new_todo += t + '\n\n'
for t in TASKS:
    new_todo += t.strip() + '\n\n'

with sftp.open('/home/hibug/lobster/todo.md', 'w') as f:
    f.write(new_todo)
sftp.close()

print("todo.md written. Verifying...")
stream(client, "grep -c '^\\[TASK' /home/hibug/lobster/todo.md && echo '---' && grep '^\\[TASK' /home/hibug/lobster/todo.md | sed 's/\\].*$/]/' | head -20")
client.close()
