import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('192.168.248.77', username='hibug', password='mug2025', timeout=10)

TODO = """\
# FORGE-Bench 龙虾任务列表
# 按顺序执行，完成一条再处理下一条
# ============================================================

[TASK-1: IMAGE AUDIT & SOURCING] Working directory: /home/hibug/FORGE-Bench. Step 1 - Audit missing images: run python3 to load dataset/annotations/samples.json, check which image_path values do not exist as actual files, print a list of missing (task_id, domain, image_path, first 100 chars of text prompt). Step 2 - For each missing image, search Wikimedia Commons using this API pattern: curl 'https://commons.wikimedia.org/w/api.php?action=query&list=search&srsearch={SUBJECT}&srnamespace=6&srlimit=5&format=json' replacing {SUBJECT} with key terms from the prompt (e.g. "Su-27 aircraft side view", "PCB circuit board", "offshore oil platform"). Step 3 - Download the best matching image (real photograph, not illustration/diagram, clearly showing the industrial subject from a suitable angle matching the prompt). Image requirements: JPG format, minimum 1280x720 pixels, 16:9 aspect ratio preferred, subject clearly visible and centered, background matches prompt description (e.g. "clear blue sky", "concrete yard", "ocean"), no watermarks. Use wget or curl to download. Rename to the exact path in image_path field. Step 4 - Verify each downloaded image: python3 -c "from PIL import Image; img=Image.open('PATH'); print(img.size, img.mode)" - confirm size >= (1280, 720). Step 5 - For any image you absolutely cannot find suitable for, create a text placeholder at the image_path location with .spec.txt extension documenting exact visual requirements. Step 6 - After adding images: git -c http.proxy=http://127.0.0.1:7897 add dataset/images/ && git -c http.proxy=http://127.0.0.1:7897 commit -m 'dataset: add reference images for missing samples'. Goal: cover at least 15 new images across all 6 domains (aerospace, microelectronics, robotics, energy, vehicle, manufacturing).

[TASK-2: SCORING REFORM] Working directory: /home/hibug/FORGE-Bench. Read eval_report context: the current hailuo-2.3 eval shows IKA=94.44, PP=97.22, VF=100 which are all unrealistically high and not discriminating. Make these SPECIFIC code changes: (1) eval/geometric_integrity/surface.py - find where GI score is computed from chamfer distance, add a minimum floor: score = max(0.10, computed_score) so no sample gets GI=0 from Chamfer alone; also add condition: if vfa_value is not None and vfa_value > 0.25, add a note in the result dict 'gi_orbit_angle_caution': True since large orbits cause legitimate perspective changes that inflate Chamfer. (2) eval/geometric_integrity/kinematic.py - fix the dark-background static detection false positive: before computing mean optical flow, check if more than 40% of pixels have value <30 (dark background); if yes, compute flow only on the center 60% ROI of the frame and use threshold 0.5px instead of 0.8px for static detection. (3) eval/physical_plausibility/eval.py - read the current LMM prompt, add this calibration instruction to it: "Apply strict scientific standards. A score of 5 requires zero physically impossible elements. Score 4: minor but physically plausible approximations only. Score 3: one noticeable but not severe physics issue. Score 2: clear violation of known physical laws. Score 1: multiple severe violations. When in doubt between two scores, choose the lower one. Industrial accuracy is paramount." (4) scoring/per_sample.py or scoring/aggregate.py - find where final per-axis scores are assembled, add a minimum floor function: for IKA, TC, PP, VF axes enforce minimum score of 5.0 (on 0-100 scale) so no axis returns exactly 0; for GI enforce minimum 10.0; this prevents zero-score edge cases while maintaining scientific validity. (5) scoring/aggregate.py - add VFA binning to the output: vfa_tier = 'none' if vfa<5 else 'weak' if vfa<20 else 'moderate' if vfa<60 else 'full'. After all changes, run python3 -m py_compile eval/geometric_integrity/surface.py eval/geometric_integrity/kinematic.py eval/physical_plausibility/eval.py scoring/per_sample.py scoring/aggregate.py to check syntax. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'scoring: scientific calibration - floor scores, orbit GI caution, dark-bg fix, strict PP'.

[TASK-3: CODE AUDIT & FIXES] Working directory: /home/hibug/FORGE-Bench. Do a systematic audit of the evaluation pipeline. (1) Read every .py file in eval/ and scoring/ directories. For each file note: (a) any bare except clauses that silently swallow errors - replace with specific exception types and proper logging, (b) any TODO/FIXME/NotImplemented that represents unfinished functionality - implement it or raise NotImplementedError with a clear message, (c) any hardcoded thresholds that should be configurable - extract to a config dict at the top of the file with comments explaining the value, (d) any function that can return None unexpectedly when downstream code doesn't handle None - add explicit None checks. (2) Specifically check eval/vfa/eval.py: does it handle missing vfa_target field gracefully? Does it handle videos shorter than 8 frames? Does it handle grayscale video input? Fix any gaps. (3) Check scoring/report.py: does it produce valid JSON? Does it handle NaN/Infinity values from CV algorithms (replace with None)? Does it generate the eval_report.json format shown in the existing results/hailuo-2.3/eval_report.json? (4) Check eval/geometric_integrity/lattice.py: the SIFT inlier ratio method - does it handle the case where too few keypoints are detected (<10 keypoints)? Add a fallback. (5) After all fixes, run: python3 -c "import eval.geometric_integrity.surface, eval.geometric_integrity.kinematic, eval.geometric_integrity.lattice, eval.physical_plausibility.eval, scoring.per_sample, scoring.aggregate, scoring.report; print('All imports OK')" and fix any import errors. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'eval: systematic audit - fix bare excepts, None handling, missing vfa_target, keypoint fallback'.

[TASK-4: EXPAND TEST SAMPLES] Working directory: /home/hibug/FORGE-Bench. Expand dataset/annotations/samples.json with new samples. Current gaps identified: (a) no tilt/rise camera motion samples exist, (b) only 1 manufacturing kinematic sample (mfg_kin_001), (c) no dolly/zoom samples, (d) vehicle domain needs more diverse subjects beyond wheel loaders (currently only def_surf variants renamed). Add exactly 10 new samples, following the EXACT JSON schema of existing samples. New samples must cover: 2 tilt/rise motion samples (one aerospace one energy), 2 manufacturing kinematic samples (different machinery - conveyor belt, robotic arm on assembly line), 2 dolly-zoom samples (one microelectronics zooming in on PCB components, one vehicle zooming in on engine bay), 2 vehicle domain samples (different vehicle types - cargo ship, mining truck), 1 energy kinematic sample (wind turbine blade rotation), 1 robotics surface sample (industrial robotic arm structure orbit). For each sample: task_id must follow pattern {domain_abbrev}_{topology}_{NNN} incrementing from existing max, failure_target must describe a specific, scientifically plausible I2V failure mode for that subject, vfa_target must use correct naming (tilt_up_Xdeg, dolly_in_Xx, rise_vertical_Xdeg), questions array must have 3-4 IKA questions testing geometric/physical constraints specific to that industrial subject, image_path set to dataset/images/{domain}/{task_id}.jpg (file does not need to exist yet), reverse=false, extra_frame=1. After adding all 10 samples, also create a spec file at dataset/images/{domain}/{task_id}_NEEDS_IMAGE.txt for each new sample describing exactly what photograph is needed (subject, angle, background, resolution min 1280x720). Run python3 -c "import json; s=json.load(open('dataset/annotations/samples.json')); print(f'Total: {len(s)} samples'); domains={}; [domains.update({x[\"domain\"]: domains.get(x[\"domain\"],0)+1}) for x in s]; print(domains)" to verify. Commit: git -c http.proxy=http://127.0.0.1:7897 add -A && git -c http.proxy=http://127.0.0.1:7897 commit -m 'dataset: add 10 new samples covering tilt/rise/dolly/vehicle/manufacturing diversity'.
"""

sftp = client.open_sftp()
with sftp.open('/home/hibug/lobster/todo.md', 'w') as f:
    f.write(TODO)
sftp.close()
print("todo.md written")

# Verify
stdin, stdout, stderr = client.exec_command('wc -l /home/hibug/lobster/todo.md && grep -c "^\\[TASK" /home/hibug/lobster/todo.md')
import sys
out = stdout.read().decode('utf-8', errors='replace')
sys.stdout.buffer.write(out.encode('gbk', errors='replace'))
client.close()
